### ISSUE TITLE
Profile belongs to the User who created it

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/ConfBuddies#21]
# Description
When someone creates a Profile, we want that profile to belong to that user.

# Changes
Inside ProfilesController, set the `user_id` to the `current_user`'s id in the create method. This can happen inside the callback `create_profile`.

**Comment by coreyhaines** [comment]
I believe this functionality should be handled here: https://github.com/ChaelCodes/ConfBuddies/blob/main/app/controllers/profiles_controller.rb#L67

**Comment by ChaelCodes** [comment]
Already completed!
