### ISSUE TITLE
Profile's handle is Unique

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/ConfBuddies#36]
# Description
We'd like to make the handles on profiles a slug in the URL, so instead of `/profiles/3` the user will see `/profiles/ChaelCodes`. In order to do this, we need to ensure the handle is unique, and url-able. This story is to validate that new profiles have unique handles, regardless of the case. If you could include some common URL checks, like removing '/', '?', and spaces, that'd be great!

# Implementation
A model-level [validation](https://guides.rubyonrails.org/active_record_validations.html#validation-helpers) on Profile that checks for the uniqueness of handle would be great.

**Comment by yagosansz** [comment]
Hi @ChaelCodes, can you assign this one to me? I think there isn't a MR for this one yet.

**Comment by ChaelCodes** [comment]
@yagosansz Thank you! You're assigned. I look forward to seeing your PR!
