### ISSUE TITLE
Improve Contributing Guide

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/ConfBuddies#47]
![image](https://user-images.githubusercontent.com/8124558/134814102-b54d689c-ecc0-4709-bd55-9705efeee7b2.png)

**Comment by LittleBigProgramming** [comment]
Can I pick this up? 😄 

I was just setting up the repo and it's been a minute since I've setup a Rails repo. 

For the most part, I'm planning to use https://github.com/ChaelCodes/HuntersKeepers/blob/main/CONTRIBUTING.md as a base and add any additional information I find along the way!

**Comment by LittleBigProgramming** [comment]
I have raised https://github.com/ChaelCodes/ConfBuddies/pull/63 to give an idea of the improvements I've made. I'm not sure if that is what this issue is after. 

Please let me know and I will update accordingly! 😀
