### ISSUE TITLE
Add Database Seeds

### ISSUE THREAD

**Issue by LittleBigProgramming** [ChaelCodes/ConfBuddies#66]
### Description
As a Developer, I would like to be able to seed my local database with example data. 

In order to get the application up and running and show example data either for local development it would be good if we could have a seed file `db/seeds.rb`, that would populate the database when we reset or run `rails db:seed`.

**Comment by LittleBigProgramming** [comment]
@ChaelCodes I would be interested in giving this a go if you like? 😄

**Comment by ChaelCodes** [comment]
@LittleBigProgramming Sounds good! We need a gem for our seeds though. One that supports data separated by embodiment.

**Comment by LittleBigProgramming** [comment]
Would something like https://github.com/faker-ruby/faker work for this? 😄  I'll take a look into it later today!

**Comment by ChaelCodes** [comment]
> Would something like https://github.com/faker-ruby/faker work for this? 😄  I'll take a look into it later today! 

Faker gives you fake data, but it doesn't seed it. It also makes data generation non-deterministic which can cause issues. For example, it might generate 2 identical handles which can't be saved.

There's also no guarantee that the fake data will be tasteful.

I'd rather we build some data that's friendly and reflects our folks, or innocuous like fictional characters.

**Comment by ChaelCodes** [comment]
@LittleBigProgramming #17 seems like a similar challenge.

**Comment by LittleBigProgramming** [comment]
No problem, I didn't see that issue when I raised this one! 

Would you lose me to close this? 😄

**Comment by ChaelCodes** [comment]
> No problem, I didn't see that issue when I raised this one! 
> 
> Would you lose me to close this? 😄 

No, it's your issue, but #72 is a PR. There must've been some confusion.
