### ISSUE TITLE
Prepend Handle with an unnecessary @

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/ConfBuddies#91]
# Description
People understand that `@` refers to a handle used to uniquely identify an individual. Names are no longer unique enough. There's too many of us.

# Changes
Put an `@` in front of the handle on the Profile show page.

Yes, this is a very small and simple issue.

**Comment by yagosansz** [comment]
Hi @ChaelCodes,

Is that okay if I take this one?
